version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - sudo npm install -g puppeteer --unsafe-perm=true
      - sudo npm install -g resume-cli
      - resume export resume.html
      - aws s3 mv resume.html s3://tjtolton.com/resume/index.html
cache:
  paths:
    - "/usr/local/lib/node_modules/**/*"