version: 0.2
phases:
  build:
    commands:
     - cd resume
#     - ls -ltrah /root/.cargo/registry
     - cargo build --release --target x86_64-unknown-linux-musl
artifacts:
  files:
   - "resume"
  discard-paths: yes
  base-directory: "$(pwd)/target/x86_64-unknown-linux-musl/release"
  name: resume
cache:
  paths:
    - "/root/.cargo/registry/**/*"
    - "$CODEBUILD_SRC_DIR/resume/target/x86_64-unknown-linux-musl/release/build/**/*"
    - "$CODEBUILD_SRC_DIR/resume/target/x86_64-unknown-linux-musl/release/deps/**/*"
