version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npx resume-cli export resume.html
      - aws s3 mv resume.html s3://tjtolton.com/resume/index.html