version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install puppeteer --unsafe-perm=true
      - npm install resume-cli
      - mkdir resume
      - npx resume export resume/index.html
      - aws cloudfront create-invalidation --distribution-id E2FHTVKFO67JA2 --paths '/resume/**/*'
artifacts:
  files:
    - resume/**/*