version: 0.2
phases:
  build:
    commands:
     - cd resume
     - ls -ltrah
#     - ls -ltrah target
#     - ls -ltrah target/x86_64-unknown-linux-musl/release
     - cargo build --release --target x86_64-unknown-linux-musl
artifacts:
  files:
   - "resume"
  discard-paths: yes
  base-directory: "$(pwd)/target/x86_64-unknown-linux-musl/release"
  name: resume
cache:
  paths:
    - "/root/.cargo/registry/**/*"
    - "resume/target/x86_64-unknown-linux-musl/release/build/**/*"
    - "resume/target/x86_64-unknown-linux-musl/release/deps/**/*"
