version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - mkdir resume
      - npm install --save jsonresume-theme-eloquent
      - node theme.js > resume/index.html
      - sed -i '8 i\<script src="https://tjtolton.com/drift.js"></script>' resume/index.html
      - cp resume/index.html resume/tjtolton.doc
      - aws cloudfront create-invalidation --distribution-id E2FHTVKFO67JA2 --paths /resume*
artifacts:
  files:
      - resume/**/*
      - drift.js
