version: 0.2
phases:
  build:
    commands:
     - cd resume
     - cargo build --release --target x86_64-unknown-linux-musl
     - mv target/x86_64-unknown-linux-musl/release/resume resume
artifacts:
  files:
   - "resume"
  discard-paths: yes
  name: resume
cache:
  paths:
    - "/root/.cargo/registry/**/*"
    - "resume/target/**/*"
