version: 0.2
phases:
  build:
    commands:
     - env
     - cd resume
#     - ls -ltrah $CODEBUILD_SRC_DIR_cargo
#     - ls -ltrah
#     - mkdir target
#     - "mv $CODEBUILD_SRC_DIR_cargo/ target/"
#     - ls -ltrah
     - cargo build --release --target x86_64-unknown-linux-musl
     - mv target/x86_64-unknown-linux-musl/release/resume target/resume
artifacts:
  files:
   - "$(pwd)/target/resume"
  discard-paths: yes
  name: resume
  secondary-artifacts:
    cargo:
      files:
        - "$(pwd)/target/x86_64-unknown-linux-musl/release/*/*"
      name: build
