version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install puppeteer --unsafe-perm=true
      - npm install resume-cli
      - npx resume export resume.html
      - aws s3 mv resume.html s3://tjtolton.com/resume/index.html
cache:
  paths:
    - "node_modules/**/*"