version: 0.2


phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Update packages and Install necessary libraries for Puppeteer
      - yum update -y
      - yum install -y libXcomposite libXi libXtst cups-libs libXScrnSaver alsa-lib atk at-spi2-atk pango gtk3
      - yum install -y mesa-libgbm  # Install the missing libgbm library

      # Ensure that we have the necessary tools installed
      - npm install -g resume-cli
      - npm install jsonresume-theme-straightforward  # Install theme locally instead of globally
      - mkdir resume

  build:
    commands:
      # Generate the HTML version of the resume
      - resume export resume/index.html --theme ./node_modules/jsonresume-theme-straightforward

      # Generate the PDF version of the resume
      - resume export resume/ML.pdf --theme ./node_modules/jsonresume-theme-straightforward --format pdf
      - aws cloudfront create-invalidation --distribution-id E2FHTVKFO67JA2 --paths /resume* /resume/ML* /login*

artifacts:
  files:
    - resume/**/*
#    - drift.js
#    - login/**/*


#version: 0.2
#phases:
#  install:
#    runtime-versions:
#      nodejs: 10
#  build:
#    commands:
#      - mkdir resume
#      - npm install --save jsonresume-theme-straightforward
#      - node theme.js > resume/index.html
#      - node themeML.js > resume/ML.html
#      -
#      # - sed -i '8 i\<script src="https://tjtolton.com/drift.js"></script>' resume/index.html

