version: 0.2
phases:
  build:
    commands:
     - env
     - cd resume
     - cd $CODEBUILD_SRC_DIR_build
     - ls -ltrah
#     - mkdir target
#     - "cp $CODEBUILD_SRC_DIR_build target"
#     - ls -ltrah target
#     - cargo build --release --target x86_64-unknown-linux-musl
#     - mv target/x86_64-unknown-linux-musl/release/resume target/resume
artifacts:
  files:
   - "resume"
  discard-paths: yes
  base-directory: "$(pwd)/target"
  name: resume
  secondary-artifacts:
    cargo:
      files:
        - "$(pwd)/target/x86_64-unknown-linux-musl/release/*/*"
      name: build
