version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install puppeteer --unsafe-perm=true
      - npm install resume-cli
      - mkdir resume
      - npx resume export resume/index.html
artifacts:
  files:
    - resume/**/*
  name: /